version: '1'

services:
  db:
    image: "mysql"
    restart: always
    environment:
      DB_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: qtec_blog
      MYSQL_USER: noon
      MYSQL_PASSWORD: passpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - my_network

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    networks:
      - my_network


volumes:
  db-data:

networks:
  my_network:
