# Generated by Django 5.0.2 on 2024-02-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '004_full_text_index_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='details',
            new_name='description',
        ),
    ]
